version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    depends_on:
      - db
    env_file:
      - .env.docker
    image: local/ffcrm
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  web:
    build: .
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'production'
      PASSENGER_APP_ENV: 'production'
  db:
    image: postgres:9.5
    ports:
      - 5432:5432
volumes:
  gems: {}
